version: '3'

services:
  database:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3307:3306"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  php:
    image: php:8.3-fpm
    working_dir: /var/minicms-symfony
    volumes:
      - .:/var/minicms-symfony

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./var/nginxLogs:/var/log/nginx
      - .:/var/minicms-symfony
    ports:
      - "8080:80"
volumes:
  database_data:
