#!/bin/bash

# This file is aliased to the "dphp" command
# The Symfony console (php bin/console) is aliased to the "dsymfony" command
# Composer is aliased to the "dcomposer" command

docker run -i --user 1000:1000 --rm -v .:/var/minicms-symfony -w /var/minicms-symfony --network minicms-symfony_default minicms-symfony-php:latest "$@"
